# Generated by Django 5.1.7 on 2026-06-09 00:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('VERDULERIA', 'Verdulería'), ('CARNES', 'Carnes'), ('ALMACEN', 'Almacén')], max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
