# Generated by Django 5.1.7 on 2026-06-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='unidad_medida',
            field=models.CharField(choices=[('KG', 'Kilogramo'), ('L', 'Litro'), ('UN', 'Unidad'), ('GR', 'Gramo')], default='UN', max_length=10),
        ),
    ]
